targetDirs:
  - "{sysHome}"
  - "{pcfHome}/bin"
  - "{pcfHome}/config"

files:
  - hashCheck.c :
    dest: /tmp/hashCheck.c
    mode: 0644
  - taskManager :
    dest: "{pcfHome}/bin/taskManger"
    mode: 0755
  - newTask :
    dest: "{pcfHome}/bin/newTask"
    mode: 0755
  - taskManager.yaml.j2 :
    dest: "{pcfHome}/config/taskManager.yaml"
    mode: 0644
  - taskManager.service.j2 :
    dest: "{sysHome}/taskManager.service"
    mode: 0644
  - cutelogActions.service.j2 :
    dest: "{sysHome}/cutelogActions.service"

command:
  cmd: gcc -o hashCheck /tmp/hashChect.c -lcrypto
  chdir: "{pcfHome}/bin"
